version: '3'
services:
  nginx-proxy:
    container_name: ops-proxy
    image: registry.udncloud.com/elmeast/nginx:1.1
    restart: always
    ports:
      - 8888:8888
      - 8089:8089
      - 8000:8000
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "tcp://10.51.2.20:514"
    #    tag: "nginx-proxy"
     
