nginx-elk:
  image: nginx
  restart: always
  ports:
    - 5601:5601
    - 44444:44444
  volumes:
    - /data/elk/Nginx/html:/usr/share/nginx/html
    - /data/elk/Nginx/nginx.conf:/etc/nginx/nginx.conf
    - /data/elk/Nginx/conf.d:/etc/nginx/conf.d
    - /data/elk/Nginx/log/:/var/log/nginx
    - /data/elk/Nginx/kibana-user:/etc/nginx/kibana-user
    - /etc/localtime:/etc/localtime:ro
   
