version: '3'
services:
  mysql-server:
 #   image: mysql:5.7.1
    image: registry.udncloud.com/zabbix/zabbix-mysql:5.7.1
    restart: always
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "Databea_zab01"
      MYSQL_ROOT_PASSWORD: "Databea_Root01"
      DB_innodb_buffer_pool_size: 1024M
    ports:
      - 10.51.2.200:3366:3306
    volumes:
      - /data/zabbix_mysql:/var/lib/mysql
      - /data/zabbix_mysql/etc/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d/
  
  zabbix-server-mysql:
#    image: zabbix/zabbix-server-mysql
    image: registry.udncloud.com/zabbix/zabbix-server-3.4-pgduty:1.1
    restart: always
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: Databea_zab01
      MYSQL_ROOT_PASSWORD: Databea_Root01
      ZBX_JAVAGATEWAY: zabbix-java-gateway
      ZBX_CACHESIZE: 1024M
      ZBX_VALUECACHESIZE: 2048M
      ZBX_TRENDCACHESIZE: 1024M
      ZBX_HISTORYCACHESIZE: 1024M
      ZBX_HISTORYINDEXCACHESIZE: 1024M
      ZBX_STARTPOLLERS: 20
    links:
      - mysql-server
    ports:
      - 10051:10051
    volumes:
      - /data/zabbix:/var/lib/zabbix
      - /data/zabbix/config/zabbix_server.conf:/etc/zabbix/zabbix_server.conf
      - /etc/localtime:/etc/localtime:ro
      - /data/zabbix/alertscripts:/usr/lib/zabbix/alertscripts/
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:514"
        syslog-facility: "local2"
        tag: "zabbix"
  
  zabbix-web-nginx:
    image: registry.udncloud.com/zabbix/zabbix-web-nginx:1.0
    restart: always
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: Databea_zab01
      PHP_TZ: Asia/Shanghai
    ports:
      - 8080:80
    links:
      - zabbix-server-mysql:zabbix-server
      - mysql-server
    volumes:
      - /data/zabbix/etc/php5:/etc/php5
      - /data/zabbix/web/fonts/ttf-dejavu:/usr/share/fonts/ttf-dejavu
      - /data/zabbix/web/nginx/conf.d:/etc/nginx/conf.d/
      - /data/zabbix/web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:514"
        syslog-facility: "local3"
        tag: "zabbix_nginx"

  
  zabbix-agent:
    image: registry.udncloud.com/zabbix/zabbix-agent:1.0
    restart: always
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: zabbix-server
    links:
      - zabbix-server-mysql:zabbix-server
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
  
  zabbix-grafana:
    image: registry.udncloud.com/zabbix/grafana:1.0
    restart: always
    ports:
      -  3000:3000
    volumes:
     - /data/zabbix_grafana:/var/lib/grafana
     - /etc/localtime:/etc/localtime:ro
