version: '2'
services:
  mysql-server-jump01:
    image: jump_mysql:5.7.3
    restart: always
    environment:
      MYSQL_DATABASE: "jump_db"
      MYSQL_USER: "jump_db"
      MYSQL_PASSWORD: "Databea_jump01"
      MYSQL_ROOT_PASSWORD: "Databea_Root01"
      DB_innodb_buffer_pool_size: 1024M
    volumes:
      - /data/jump_mysql_01:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  jump-server01:
    image: jumpserver/jumpserver:0.5.0-beta2
    restart: always
    environment:
      DB_ENGINE: mysql
      DB_HOST: mysql-server-jump01
      DB_PORT: 3306
      DB_USER: jump_db
      DB_NAME: jump_db
      DB_PASSWORD: Databea_jump01
    ports:
      - 10080:80
      - 2222:2222
    links:
      - mysql-server-jump01
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/jumpserver01:/opt/jumpserver/data
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:514"
        syslog-facility: "local4"
