ql-server:
  image: mysql:5.7.2
  restart: always
  ports:
    - 3306:3306
  environment:
    MYSQL_DATABASE: "jump_db"
    MYSQL_USER: "jump_db"
    MYSQL_PASSWORD: "Databea_jump01"
    MYSQL_ROOT_PASSWORD: "Databea_Root01"
  volumes:
    - /data/jump_mysql:/var/lib/mysql
