---
  # name:create user
  - hosts: all
    become: yes
    become_user: root
    become_method: sudo
    roles:
      - {{ roles }}
#
#   #name : install zabbix-agent
#  - hosts: {{ zabbix_agent }}
#    become: yes
#    become_user: root
#    become_method: sudo
#    roles:
#      - zabbix-agent
